export const ADMIN_EMAILS = ['sarath.s1884@gmail.com'];

// Encryption salt for E2E message encryption key derivation
export const ENCRYPTION_SALT = 'sangam_e2e_v1_salt';

export const AVATAR_OPTIONS = [
  '🧑',
  '👩',
  '👨',
  '👧',
  '🧒',
  '👵',
  '🧓',
  '👴',
  '🧔',
  '👱',
  '👲',
  '🧕',
  '👳',
  '💁',
  '🙋',
  '🤷',
  '🦸',
  '🧑‍💻',
  '👩‍💻',
  '👨‍💻',
  '👩‍🎓',
  '👨‍🎓',
  '👩‍🏫',
  '👨‍⚕️',
];

// 3-tier ethnicity hierarchy: Region → Sub-region → Specific Ethnicities
// Ordered by most commonly used / largest diaspora populations first
export const ETHNICITY_HIERARCHY: { region: string; subregions: { name: string; ethnicities: string[] }[] }[] = [
  { region: 'Asian', subregions: [
    { name: 'South Asian', ethnicities: ['Indian', 'Pakistani', 'Bangladeshi', 'Sri Lankan', 'Nepali', 'Bhutanese', 'Maldivian', 'Afghan'] },
    { name: 'East Asian', ethnicities: ['Chinese', 'Japanese', 'Korean', 'Taiwanese', 'Mongolian', 'Tibetan', 'Hong Konger'] },
    { name: 'Southeast Asian', ethnicities: ['Filipino', 'Vietnamese', 'Indonesian', 'Thai', 'Malaysian', 'Burmese', 'Cambodian', 'Laotian', 'Singaporean', 'Hmong'] },
    { name: 'Central Asian', ethnicities: ['Kazakh', 'Uzbek', 'Tajik', 'Kyrgyz', 'Turkmen'] },
  ]},
  { region: 'Hispanic or Latino', subregions: [
    { name: 'Mexican', ethnicities: ['Mexican', 'Mexican American', 'Chicano'] },
    { name: 'Caribbean', ethnicities: ['Puerto Rican', 'Cuban', 'Dominican', 'Jamaican', 'Haitian', 'Trinidadian', 'Barbadian', 'Bahamian'] },
    { name: 'South American', ethnicities: ['Brazilian', 'Colombian', 'Argentine', 'Peruvian', 'Venezuelan', 'Chilean', 'Ecuadorian', 'Bolivian', 'Paraguayan', 'Uruguayan', 'Guyanese', 'Surinamese'] },
    { name: 'Central American', ethnicities: ['Salvadoran', 'Guatemalan', 'Honduran', 'Nicaraguan', 'Costa Rican', 'Panamanian', 'Belizean'] },
    { name: 'Spanish', ethnicities: ['Spanish (from Spain)'] },
  ]},
  { region: 'European', subregions: [
    { name: 'Western European', ethnicities: ['English', 'German', 'French', 'Irish', 'Dutch', 'Belgian', 'Swiss', 'Austrian', 'Scottish', 'Welsh', 'Luxembourgish'] },
    { name: 'Southern European', ethnicities: ['Italian', 'Spanish', 'Greek', 'Portuguese', 'Croatian', 'Serbian', 'Albanian', 'Maltese', 'Bosnian', 'Montenegrin', 'Slovenian', 'Macedonian', 'Cypriot'] },
    { name: 'Eastern European', ethnicities: ['Russian', 'Polish', 'Ukrainian', 'Romanian', 'Czech', 'Hungarian', 'Bulgarian', 'Slovak', 'Belarusian', 'Moldovan', 'Georgian', 'Armenian'] },
    { name: 'Northern European', ethnicities: ['Swedish', 'Norwegian', 'Danish', 'Finnish', 'Icelandic', 'Estonian', 'Latvian', 'Lithuanian'] },
  ]},
  { region: 'African', subregions: [
    { name: 'African American / Black British', ethnicities: ['African American', 'Black British', 'Afro-Caribbean', 'Afro-Latino'] },
    { name: 'West African', ethnicities: ['Nigerian', 'Ghanaian', 'Senegalese', 'Ivorian', 'Malian', 'Sierra Leonean', 'Liberian', 'Guinean', 'Togolese', 'Beninese', 'Burkinabe', 'Gambian', 'Cape Verdean'] },
    { name: 'East African', ethnicities: ['Ethiopian', 'Kenyan', 'Somali', 'Tanzanian', 'Ugandan', 'Rwandan', 'Eritrean', 'Burundian', 'South Sudanese', 'Djiboutian'] },
    { name: 'North African', ethnicities: ['Egyptian', 'Moroccan', 'Algerian', 'Tunisian', 'Libyan', 'Sudanese'] },
    { name: 'Southern African', ethnicities: ['South African', 'Zimbabwean', 'Motswana', 'Namibian', 'Mozambican', 'Zambian', 'Malawian', 'Swazi', 'Basotho', 'Malagasy'] },
    { name: 'Central African', ethnicities: ['Congolese', 'Cameroonian', 'Angolan', 'Chadian', 'Gabonese', 'Central African', 'Equatorial Guinean'] },
  ]},
  { region: 'Middle Eastern', subregions: [
    { name: 'Levantine', ethnicities: ['Lebanese', 'Syrian', 'Palestinian', 'Jordanian', 'Iraqi'] },
    { name: 'Arabian Peninsula', ethnicities: ['Saudi', 'Emirati', 'Kuwaiti', 'Qatari', 'Bahraini', 'Omani', 'Yemeni'] },
    { name: 'Persian / Iranian', ethnicities: ['Persian', 'Iranian', 'Kurdish'] },
    { name: 'Turkish', ethnicities: ['Turkish'] },
    { name: 'Israeli / Jewish', ethnicities: ['Israeli', 'Ashkenazi Jewish', 'Sephardic Jewish', 'Mizrahi Jewish'] },
  ]},
  { region: 'Oceanian / Pacific Islander', subregions: [
    { name: 'Polynesian', ethnicities: ['Native Hawaiian', 'Samoan', 'Tongan', 'Maori', 'Tahitian', 'Cook Islander'] },
    { name: 'Melanesian', ethnicities: ['Fijian', 'Papua New Guinean', 'Solomon Islander', 'Ni-Vanuatu', 'New Caledonian'] },
    { name: 'Micronesian', ethnicities: ['Chamorro', 'Guamanian', 'Marshallese', 'Palauan', 'Chuukese', 'Kosraean'] },
    { name: 'Australian', ethnicities: ['Australian'] },
    { name: 'New Zealander', ethnicities: ['New Zealander', 'Pakeha'] },
  ]},
  { region: 'Indigenous & Native People', subregions: [
    { name: 'Native American / Alaska Native', ethnicities: ['Native American', 'Alaska Native', 'Cherokee', 'Navajo', 'Sioux', 'Ojibwe', 'Apache'] },
    { name: 'First Nations / Inuit / Métis', ethnicities: ['First Nations', 'Inuit', 'Métis'] },
    { name: 'Aboriginal / Torres Strait Islander', ethnicities: ['Aboriginal Australian', 'Torres Strait Islander'] },
    { name: 'Maori', ethnicities: ['Maori'] },
    { name: 'Sámi', ethnicities: ['Sámi'] },
    { name: 'Ainu', ethnicities: ['Ainu'] },
  ]},
  { region: 'Multiracial & Other', subregions: [
    { name: 'Multiracial', ethnicities: ['Two or More Races', 'Multiracial', 'Biracial'] },
    { name: 'Not Listed', ethnicities: ['Other / Ethnicity not listed'] },
  ]},
  { region: 'Prefer Not to Say', subregions: [
    { name: 'Privacy', ethnicities: ['Prefer not to say', 'Decline to self-identify'] },
  ]},
];

// Sub-items under specific ethnicities (e.g., Indian states)
export const ETHNICITY_CHILDREN: Record<string, string[]> = {
  'Indian': [
    'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
    'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand',
    'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
    'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
    'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura',
    'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  ],
};

// Flat lists derived from hierarchy (backward-compatible exports)
export const HERITAGE_OPTIONS = [
  ...ETHNICITY_HIERARCHY.flatMap(r => r.subregions.flatMap(s => s.ethnicities)),
  ...Object.values(ETHNICITY_CHILDREN).flat(),
];
export const ETHNICITY_OPTIONS = HERITAGE_OPTIONS;

// Mapping of common terms to ethnicity suggestions for auto-suggest
export const ETHNICITY_KEYWORDS: Record<string, string[]> = {
  african: ['African American', 'Ethiopian', 'Nigerian', 'Ghanaian'],
  black: ['African American', 'Black British', 'Afro-Caribbean'],
  indian: ['Indian'], pakistani: ['Pakistani'], bangladeshi: ['Bangladeshi'],
  chinese: ['Chinese'], japanese: ['Japanese'], korean: ['Korean'],
  vietnamese: ['Vietnamese'], filipino: ['Filipino'], thai: ['Thai'],
  indonesian: ['Indonesian'], malaysian: ['Malaysian'], hmong: ['Hmong'],
  mexican: ['Mexican', 'Mexican American'], cuban: ['Cuban'], colombian: ['Colombian'],
  brazilian: ['Brazilian'], argentine: ['Argentine'], peruvian: ['Peruvian'],
  italian: ['Italian'], german: ['German'], french: ['French'],
  irish: ['Irish'], english: ['English'], scottish: ['Scottish'],
  russian: ['Russian'], polish: ['Polish'], ukrainian: ['Ukrainian'],
  armenian: ['Armenian'], georgian: ['Georgian'],
  lebanese: ['Lebanese'], syrian: ['Syrian'], iranian: ['Iranian', 'Persian'],
  turkish: ['Turkish'], kurdish: ['Kurdish'], israeli: ['Israeli'],
  jewish: ['Ashkenazi Jewish', 'Sephardic Jewish', 'Mizrahi Jewish'],
  hawaiian: ['Native Hawaiian'], samoan: ['Samoan'], fijian: ['Fijian'],
  aboriginal: ['Aboriginal Australian'], maori: ['Maori'],
  native: ['Native American', 'Alaska Native', 'Native Hawaiian'],
  nepali: ['Nepali'], afghan: ['Afghan'],
  sri_lankan: ['Sri Lankan'], bhutanese: ['Bhutanese'], maldivian: ['Maldivian'],
  eritrean: ['Eritrean'], somali: ['Somali'], ethiopian: ['Ethiopian'],
  nigerian: ['Nigerian'], ghanaian: ['Ghanaian'],
};

export const POST_TYPES = ['community', 'question', 'recommendation', 'event', 'news'];

export const BUSINESS_CATEGORIES = [
  'Restaurant',
  'Grocery',
  'Technology',
  'Healthcare',
  'Education',
  'Real Estate',
  'Legal',
  'Financial',
  'Beauty & Spa',
  'Automotive',
  'Home Services',
  'Religious/Spiritual',
  'Entertainment',
  'Fitness',
  'Retail',
  'Other',
];

// Extended business types for signup registration
export const BUSINESS_TYPES = [
  'Agriculture & Farming',
  'Arts & Entertainment',
  'Automotive',
  'Beauty & Wellness',
  'Boutique',
  'Clothing / Fashion',
  'Construction',
  'Education & Tutoring',
  'Financial Services',
  'Fitness & Gym',
  'Grocery & Market',
  'Healthcare / Medical',
  'Henna',
  'Home Services',
  'Hotels',
  'Jewelry',
  'Legal & Immigration',
  'Media & Advertising',
  'Non-Profit',
  'Real Estate / Property',
  'Religious / Spiritual',
  'Restaurant & Food',
  'Retail / E-Commerce',
  'Technology / IT Services',
  'Tiffin',
  'Transportation & Logistics',
  'Travel & Tourism',
  'Other',
];

export const EVENT_TYPES = [
  'Cultural',
  'Community',
  'Religious',
  'Sports',
  'Educational',
  'Networking',
  'Family',
  'Music',
  'Food',
  'Other',
];

export const LISTING_TYPES = ['rent', 'sale', 'roommate', 'sublet'];

export interface ForumTopic {
  id: string;
  name: string;
  icon: string;
  description: string;
}

export const FORUM_TOPICS: ForumTopic[] = [
  { id: 'immigration', name: 'Immigration & Visa', icon: '📋', description: 'H1B, green card, citizenship, visa queries' },
  { id: 'career', name: 'Career & Jobs', icon: '💼', description: 'Job search, interviews, career advice, networking' },
  { id: 'finance', name: 'Finance & Taxes', icon: '💰', description: 'Investing, tax filing, remittances, FBAR/FATCA' },
  { id: 'parenting', name: 'Parenting & Family', icon: '👨‍👩‍👧‍👦', description: 'Raising kids bicultural, schools, family dynamics' },
  { id: 'food', name: 'Food & Recipes', icon: '🍛', description: 'Regional recipes, grocery finds, restaurant reviews' },
  { id: 'health', name: 'Health & Wellness', icon: '🏥', description: 'Finding doctors, Ayurveda, mental health, insurance' },
  { id: 'education', name: 'Education', icon: '🎓', description: 'College admissions, test prep, tutoring, STEM programs' },
  { id: 'relationships', name: 'Relationships & Marriage', icon: '💑', description: 'Dating, wedding planning, cultural expectations' },
  { id: 'religion', name: 'Religion & Spirituality', icon: '🙏', description: 'Temples, mosques, gurdwaras, festivals, spiritual practice' },
  { id: 'sports', name: 'Sports & Cricket', icon: '🏏', description: 'IPL, cricket leagues, badminton, local sports' },
  { id: 'entertainment', name: 'Entertainment', icon: '🎬', description: 'Bollywood, regional cinema, music, streaming' },
  { id: 'technology', name: 'Technology & Startups', icon: '💻', description: 'Tech careers, startups, AI/ML, coding' },
  { id: 'legal', name: 'Legal Advice', icon: '⚖️', description: 'Immigration law, tenant rights, general legal questions' },
  { id: 'civic', name: 'Civic & Politics', icon: '🗳️', description: 'Voter info, community organizing, policy advocacy' },
  { id: 'general', name: 'General Discussion', icon: '💬', description: 'Anything else, off-topic, community announcements' },
];

export const REPORT_REASONS = [
  { id: 'hate_speech', label: 'Hate Speech', description: 'Content targeting race, ethnicity, religion, or caste' },
  { id: 'harassment', label: 'Harassment', description: 'Bullying, threats, or personal attacks' },
  { id: 'spam', label: 'Spam', description: 'Unwanted promotional or repetitive content' },
  { id: 'explicit', label: 'Explicit Content', description: 'Sexual or graphic violence content' },
  { id: 'misinformation', label: 'Misinformation', description: 'False or misleading information' },
  { id: 'scam', label: 'Scam / Fraud', description: 'Phishing, financial fraud, or scam attempts' },
  { id: 'other', label: 'Other', description: 'Something else that violates community guidelines' },
];

export const US_STATES_CITIES: Record<string, string[]> = {
  Utah: [
    'Salt Lake City',
    'Sandy',
    'Draper',
    'Murray',
    'Provo',
    'Orem',
    'Lehi',
    'Layton',
    'West Jordan',
    'West Valley City',
    'American Fork',
    'South Jordan',
    'Riverton',
    'Taylorsville',
    'Logan',
    'Ogden',
    'Farmington',
    'Roy',
    'Kaysville',
    'Bountiful',
    'Centerville',
    'Sugarhouse',
    'Park City',
    'Moab',
    'Spanish Fork',
    'Salem',
    'Mapleton',
    'Saratoga Springs',
    'Cedar Hills',
    'Herriman',
    'Eagle Mountain',
    'Payson',
    'Ephraim',
    'Manti',
    'Gunnison',
    'Salina',
    'Richfield',
  ],
  California: [
    'Los Angeles',
    'San Francisco',
    'San Diego',
    'Sacramento',
    'Long Beach',
    'Oakland',
    'Fresno',
    'Bakersfield',
    'Anaheim',
    'Santa Ana',
    'Riverside',
    'Stockton',
    'Irvine',
    'Santa Clarita',
    'Chula Vista',
    'San Bernardino',
    'Fontana',
    'Moreno Valley',
    'Glendale',
    'Huntington Park',
  ],
  Texas: [
    'Houston',
    'Dallas',
    'Austin',
    'San Antonio',
    'Fort Worth',
    'Arlington',
    'Corpus Christi',
    'Plano',
    'Garland',
    'Irving',
    'Laredo',
    'Lubbock',
    'Amarillo',
    'Brownsville',
    'Tyler',
  ],
  'New York': [
    'New York City',
    'Buffalo',
    'Rochester',
    'Yonkers',
    'Syracuse',
    'Albany',
    'Schenectady',
    'New Rochelle',
    'Troy',
    'Niagara Falls',
  ],
  'New Jersey': [
    'Newark',
    'Jersey City',
    'Paterson',
    'Elizabeth',
    'Trenton',
    'Atlantic City',
    'Camden',
    'Clifton',
    'Irvington',
    'Passaic',
  ],
  Illinois: [
    'Chicago',
    'Aurora',
    'Rockford',
    'Joliet',
    'Naperville',
    'Springfield',
    'Peoria',
    'Elgin',
    'Waukegan',
    'Cicero',
  ],
  Washington: [
    'Seattle',
    'Spokane',
    'Tacoma',
    'Vancouver',
    'Bellevue',
    'Kent',
    'Everett',
    'Renton',
    'Kirkland',
    'Sammamish',
  ],
  Georgia: [
    'Atlanta',
    'Augusta',
    'Columbus',
    'Savannah',
    'Macon',
    'Sandy Springs',
    'Johns Creek',
    'Marietta',
    'Alpharetta',
    'Roswell',
  ],
  Virginia: [
    'Virginia Beach',
    'Richmond',
    'Arlington',
    'Alexandria',
    'Blacksburg',
    'Charlottesville',
    'Roanoke',
    'Leesburg',
    'Fairfax',
    'Falls Church',
  ],
  Maryland: [
    'Baltimore',
    'Frederick',
    'Gaithersburg',
    'Bowie',
    'Annapolis',
    'College Park',
    'Towson',
    'Silver Spring',
    'Bethesda',
    'Takoma Park',
  ],
  Pennsylvania: [
    'Philadelphia',
    'Pittsburgh',
    'Allentown',
    'Erie',
    'Reading',
    'Scranton',
    'Bethlehem',
    'Lancaster',
    'Harrisburg',
    'Altoona',
  ],
  Massachusetts: [
    'Boston',
    'Worcester',
    'Springfield',
    'Cambridge',
    'Providence',
    'Somerville',
    'Lowell',
    'Brockton',
    'Quincy',
    'Lynn',
  ],
  Florida: [
    'Jacksonville',
    'Miami',
    'Tampa',
    'Orlando',
    'St. Petersburg',
    'Hialeah',
    'Tallahassee',
    'Fort Lauderdale',
    'Port St. Lucie',
    'Ft. Myers',
  ],
  Ohio: [
    'Columbus',
    'Cleveland',
    'Cincinnati',
    'Toledo',
    'Akron',
    'Dayton',
    'Youngstown',
    'Canton',
    'Gahanna',
    'Parma',
  ],
  Michigan: [
    'Detroit',
    'Grand Rapids',
    'Warren',
    'Sterling Heights',
    'Ann Arbor',
    'Lansing',
    'Flint',
    'Dearborn',
    'Livonia',
    'Westland',
  ],
  'North Carolina': [
    'Charlotte',
    'Raleigh',
    'Greensboro',
    'Durham',
    'Chapel Hill',
    'Wilmington',
    'High Point',
    'Fayetteville',
    'Cary',
    'Winston-Salem',
  ],
  Arizona: [
    'Phoenix',
    'Mesa',
    'Scottsdale',
    'Chandler',
    'Glendale',
    'Tempe',
    'Peoria',
    'Gilbert',
    'Tucson',
    'Casas Adobes',
  ],
  Colorado: [
    'Denver',
    'Colorado Springs',
    'Aurora',
    'Fort Collins',
    'Lakewood',
    'Pueblo',
    'Arvada',
    'Littleton',
    'Westminster',
    'Boulder',
  ],
  Oregon: [
    'Portland',
    'Eugene',
    'Salem',
    'Gresham',
    'Hillsboro',
    'Bend',
    'Beaverton',
    'Medford',
    'Springfield',
    'Corvallis',
  ],
  Minnesota: [
    'Minneapolis',
    'Saint Paul',
    'Rochester',
    'Duluth',
    'Saint Cloud',
    'Bloomington',
    'Edina',
    'Minnetonka',
    'Plymouth',
    'Maple Grove',
  ],
  Connecticut: [
    'Bridgeport',
    'New Haven',
    'Hartford',
    'Stamford',
    'Waterbury',
    'Norwalk',
    'Danbury',
    'New Britain',
    'West Hartford',
    'Meriden',
  ],
  Tennessee: [
    'Nashville',
    'Memphis',
    'Knoxville',
    'Chattanooga',
    'Clarksville',
    'Murfreesboro',
    'Franklin',
    'Jackson',
    'Johnson City',
    'Kingsport',
  ],
  'Canada': ['Toronto', 'Vancouver', 'Brampton', 'Mississauga', 'Surrey', 'Calgary', 'Edmonton', 'Ottawa', 'Montreal'],
  'United Kingdom': ['London', 'Birmingham', 'Leicester', 'Manchester', 'Leeds', 'Bradford', 'Glasgow', 'Edinburgh'],
  'Australia': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Canberra'],
  'UAE': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman'],
  'Singapore': ['Singapore'],
  'Germany': ['Berlin', 'Munich', 'Frankfurt', 'Hamburg'],
  'New Zealand': ['Auckland', 'Wellington', 'Christchurch'],
};

export const ZIP_TO_CITY_STATE: Record<string, { city: string; state: string }> = {
  '84101': { city: 'Salt Lake City', state: 'Utah' },
  '84102': { city: 'Salt Lake City', state: 'Utah' },
  '84103': { city: 'Salt Lake City', state: 'Utah' },
  '84104': { city: 'Salt Lake City', state: 'Utah' },
  '84105': { city: 'Salt Lake City', state: 'Utah' },
  '84106': { city: 'Salt Lake City', state: 'Utah' },
  '84107': { city: 'Salt Lake City', state: 'Utah' },
  '84108': { city: 'Salt Lake City', state: 'Utah' },
  '84109': { city: 'Salt Lake City', state: 'Utah' },
  '84110': { city: 'Salt Lake City', state: 'Utah' },
  '84111': { city: 'Salt Lake City', state: 'Utah' },
  '84112': { city: 'Salt Lake City', state: 'Utah' },
  '84113': { city: 'Salt Lake City', state: 'Utah' },
  '84114': { city: 'Salt Lake City', state: 'Utah' },
  '84115': { city: 'Salt Lake City', state: 'Utah' },
  '84116': { city: 'Salt Lake City', state: 'Utah' },
  '84117': { city: 'Salt Lake City', state: 'Utah' },
  '84118': { city: 'Salt Lake City', state: 'Utah' },
  '84119': { city: 'Salt Lake City', state: 'Utah' },
  '84120': { city: 'Salt Lake City', state: 'Utah' },
  '84121': { city: 'Sandy', state: 'Utah' },
  '84122': { city: 'Sandy', state: 'Utah' },
  '84123': { city: 'Sandy', state: 'Utah' },
  '84124': { city: 'Draper', state: 'Utah' },
  '84125': { city: 'Murray', state: 'Utah' },
  '84126': { city: 'West Jordan', state: 'Utah' },
  '84127': { city: 'West Jordan', state: 'Utah' },
  '84128': { city: 'Riverton', state: 'Utah' },
  '84129': { city: 'Herriman', state: 'Utah' },
  '84130': { city: 'Taylorsville', state: 'Utah' },
  '84131': { city: 'Taylorsville', state: 'Utah' },
  '84132': { city: 'South Jordan', state: 'Utah' },
  '84133': { city: 'South Jordan', state: 'Utah' },
  '84134': { city: 'West Valley City', state: 'Utah' },
  '84135': { city: 'West Valley City', state: 'Utah' },
  '84136': { city: 'West Valley City', state: 'Utah' },
  '84137': { city: 'West Valley City', state: 'Utah' },
  '84138': { city: 'American Fork', state: 'Utah' },
  '84139': { city: 'Lehi', state: 'Utah' },
  '84141': { city: 'Orem', state: 'Utah' },
  '84142': { city: 'Orem', state: 'Utah' },
  '84143': { city: 'Orem', state: 'Utah' },
  '84144': { city: 'Provo', state: 'Utah' },
  '84145': { city: 'Provo', state: 'Utah' },
  '84146': { city: 'Provo', state: 'Utah' },
  '84147': { city: 'Provo', state: 'Utah' },
  '84148': { city: 'Provo', state: 'Utah' },
  '84150': { city: 'Provo', state: 'Utah' },
  '84157': { city: 'Provo', state: 'Utah' },
  '84158': { city: 'Provo', state: 'Utah' },
  '84160': { city: 'Salt Lake City', state: 'Utah' },
  '84161': { city: 'Salt Lake City', state: 'Utah' },
  '84170': { city: 'Salt Lake City', state: 'Utah' },
  '84180': { city: 'Salt Lake City', state: 'Utah' },
  '84190': { city: 'Salt Lake City', state: 'Utah' },
  '84199': { city: 'Salt Lake City', state: 'Utah' },
  '84201': { city: 'Ogden', state: 'Utah' },
  '84202': { city: 'Ogden', state: 'Utah' },
  '84203': { city: 'Ogden', state: 'Utah' },
  '84204': { city: 'Ogden', state: 'Utah' },
  '84207': { city: 'Layton', state: 'Utah' },
  '84208': { city: 'Farmington', state: 'Utah' },
  '84209': { city: 'Kaysville', state: 'Utah' },
  '84210': { city: 'Bountiful', state: 'Utah' },
  '84211': { city: 'Logan', state: 'Utah' },
  '84221': { city: 'Park City', state: 'Utah' },
  '84760': { city: 'Moab', state: 'Utah' },
  '84761': { city: 'Moab', state: 'Utah' },
};
